#!/usr/bin/env bash

sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx to listen on port 80 and return the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart nginx
sudo service nginx restart
