#!/usr/bin/env bash

sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx to listen on port 80 and return the string "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Start nginx
sudo service nginx start
