#!/usr/bin/env bash
# Configure your Nginx server so /redirect_me is redirecting to another page
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure nginx to listen on port 80 and redirect /redirect_me
sudo sed -i "s|listen 80 default_server;|listen 80 default_server;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;\n\t}|" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
