#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

#!/usr/bin/env bash
#Install nginx on your server
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx to listen on port 80 and redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "30i 

# Restart nginx
sudo service nginx restart
