#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
# Install nginx on your server
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx to listen on port 80 and redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Modify Nginx config file to use custom 404 page
sudo sed -i 's/#error_page 404 \/404.html;/error_page 404 \/404.html;/' /etc/nginx/sites-available/default
sudo sed -i 's/#location = \/404.html {/location = \/404.html {/' /etc/nginx/sites-available/default
sudo sed -i 's/#    internal;/    internal;/' /etc/nginx/sites-available/default
sudo sed -i 's/#}/}/' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
