#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update and upgrade the package list
sudo apt-get update

sudo apt-get upgrade

# Install Nginx
sudo apt-get install -y nginx

# Redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure nginx to listen on port 80 and redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# Configure nginx to listen on port 80 and redirect /redirect_me
sudo sed -i "41i\rewrite ^/redirect_me https://github.com permanent;" /etc/nginx/sites-enabled/default

# Modify Nginx config file to use custom 404 page
sudo sed -i "30i \\\terror_page 404 /error_404.html;" /etc/nginx/sites-enabled/default

# Custom HTTP header
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
