#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

# Update the package list
sudo apt-get update

# Install haproxy
sudo apt-get install -y haproxy

# Configure haproxy to loadbalance between the 2 servers
# Enable haproxy to be managed by init script
echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option http-keep-alive
   option forwardfor
   server 12682-web-01 54.90.37.210:80 check
   server 12682-web-02 	100.25.137.138:80 check
" >> /etc/haproxy/haproxy.cfg

# Restart haproxy
sudo service haproxy restart
