#!/usr/bin/env bash
#A script that generates a MySQL dump and creates a compressed archive out of it

sudo mysqldump --user=root --password="$1" --all-databases > backup.sql
tar -cvzf "$(date +"%d-%m-%Y").tar.gz" backup.sql
