#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
# with a sleep 2 in between each iteration

n=0
while [ $n -le 3 ]
do
	trap "echo I am  invincible!!!" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
